### PR TITLE
completed html and css part of assignment

### PR DESCRIPTION
**Pull request by Saiprabhu007**
Completed the html and css part of the assignment .

### CODE REVIEW

**Review by KrishnaSaiVadlamani — COMMENTED** [review]
what is this assignment about?

**Comment by Saiprabhu007** [comment]
Creation of  portfolio website

**Comment by KrishnaSaiVadlamani** [comment]
where is the code in it? i cant see any code

**Comment by Saiprabhu007** [comment]
Is it not present in index.html

**Comment by Saiprabhu007** [comment]
All the code is available  in index.html , style.css, contactme.html, aboutme.html,my-gallery.html  files sir

**Comment by KrishnaSaiVadlamani** [comment]
i could only able to see 1 file. please try to push those files again

**Comment by Saiprabhu007** [comment]
but sir i have pushed  the total folder regarding the assignment

**Comment by Saiprabhu007** [comment]
i will try to push it again

**Comment by KrishnaSaiVadlamani** [comment]
But there is no folder in it, try it to push it again

**Pull request closed without merging**
